imas/rdflint

README.md
build.gradle
example/dataset/RDFs/765AS.rdf
example/dataset/rdflint-config.yml
src/main/java/com/github/takemikami/rdflint/CustomRule.java
src/main/java/com/github/takemikami/rdflint/RDFLint.java
src/main/java/com/github/takemikami/rdflint/RDFLintParameters.java
src/test/java/com/github/takemikami/rdflint/RDFLintTest.java
src/test/resources/testRDFs/config_ng/rdflint-config.yml
src/test/resources/testRDFs/config_ng/valid.rdf
src/test/resources/testRDFs/config_ok/rdflint-config.yml
src/test/resources/testRDFs/config_ok/valid.rdf

add valid function by sparql

---

src/main/java/com/github/takemikami/rdflint/RDFLint.java
src/main/resources/schemaorg/3.3/all-layers.ttl
src/main/resources/schemaorg/3.4/all-layers.ttl
src/test/java/com/github/takemikami/rdflint/RDFLintTest.java
src/test/resources/testRDFs/undefinedsubject_resource/undefinedsubject_resource.rdf

for check schema.org vocabulary 
add schema.org ttl, and check logic.
_Links to blog posts, patterns, libraries or addons used to solve this problem_

add schema.org check

---

build.gradle
src/main/resources/log4j.properties

surpress warning of log4j
add log4j config
_Links to blog posts, patterns, libraries or addons used to solve this problem_

surpress log4j warnings

---

README.md

prepare to 0.0.3
update readme
_Links to blog posts, patterns, libraries or addons used to solve this problem_

upgrade to 0.0.3

---

LICENSE
build.gradle
src/main/java/com/github/imas/rdflint/CustomRule.java
src/main/java/com/github/imas/rdflint/LintProblem.java
src/main/java/com/github/imas/rdflint/LintProblemSet.java
src/main/java/com/github/imas/rdflint/ProblemLogger.java
src/main/java/com/github/imas/rdflint/RdfLint.java
src/main/java/com/github/imas/rdflint/RdfLintParameters.java
src/test/java/com/github/imas/rdflint/RdfLintTest.java

transfer rdflint to IM@Study
- rename package name.
- change LICENSE owner

rename package takemikami to imas

---

README.md

for easy to understand to use rdflint.
add explanation to readme.

add explanation of use to readme

---

README.md
build.gradle
src/main/java/com/github/imas/rdflint/InteractiveParser.java
src/main/java/com/github/imas/rdflint/RdfLint.java

for try to query before pull request.
add interactive mode.

add interactive mode

---

README.md

prepare to 0.0.4
update readme

prepare to 0.0.4

---

README.md
src/main/java/com/github/imas/rdflint/InteractiveParser.java
src/main/java/com/github/imas/rdflint/RdfLint.java

enhance interactive mode: validation and reload
implements following functions to interactive mode:
- reaload dataset
- execute validation

enhance interactive mode: validation and reload

---

src/main/java/com/github/imas/rdflint/LintProblem.java
src/main/java/com/github/imas/rdflint/LintProblemSet.java
src/main/java/com/github/imas/rdflint/ProblemLogger.java
src/main/java/com/github/imas/rdflint/RdfLint.java
src/main/java/com/github/imas/rdflint/config/CustomRule.java
src/main/java/com/github/imas/rdflint/config/RdfLintParameters.java
src/main/java/com/github/imas/rdflint/validator/AbstractRdfValidator.java
src/main/java/com/github/imas/rdflint/validator/RdfValidator.java
src/main/java/com/github/imas/rdflint/validator/impl/CustomQueryValidator.java
src/main/java/com/github/imas/rdflint/validator/impl/DegradeValidator.java
src/main/java/com/github/imas/rdflint/validator/impl/RdfSyntaxValidator.java
src/main/java/com/github/imas/rdflint/validator/impl/UndefinedSubjectValidator.java
src/test/java/com/github/imas/rdflint/RdfLintTest.java
src/test/resources/testRDFs/originxml/origin.rdf

split main routine and validation implementation, for easy to add new validation logic.
move validation implementation to 'com.github.imas.rdflint.validator.impl' package.

split main routine and validation implementation

---

build.gradle
src/main/java/com/github/imas/rdflint/RdfLint.java
src/main/java/com/github/imas/rdflint/config/GenerationRule.java
src/main/java/com/github/imas/rdflint/config/RdfLintParameters.java
src/test/java/com/github/imas/rdflint/RdfLintTest.java
src/test/resources/testRDFs/config_genok/rdflint-config.yml
src/test/resources/testRDFs/config_genok/sample.rdf.template
src/test/resources/testRDFs/config_genok/valid.rdf

add rdf generation function
add rdf generation function, following process
- load dataset
- execute SPARQL query
- generate rdf with query result-set

new function: rdf generation

---

README.md

prepare to 0.0.5
update README

prepare to 0.0.5

---

README.md
build.gradle

package build bugfix
https://jitpack.io/com/github/imas/rdflint/0.0.5/build.log
remove application from build.gradle

package build bugfix

---

README.md
src/main/java/com/github/imas/rdflint/RdfLint.java
src/main/java/com/github/imas/rdflint/validator/impl/TrimValidator.java
src/test/java/com/github/imas/rdflint/RdfLintTest.java
src/test/resources/testRDFs/needtrim/needtrim.rdf

fix #25
validate "Need to trim literal" 
Implement TrimValidator

add trimvalidator

---

README.md
docs/setup.md
docs/usage.md

prepare-0.0.7

---

src/main/java/com/github/imas/rdflint/RdfLint.java
src/main/java/com/github/imas/rdflint/validator/impl/DataTypeValidator.java
src/test/java/com/github/imas/rdflint/RdfLintTest.java
src/test/resources/testRDFs/datatype_ng/datatype_ng.rdf
src/test/resources/testRDFs/datatype_ok/datatype_ok.rdf

add datatype validator

---

src/main/java/com/github/imas/rdflint/utils/StatsTestUtils.java
src/main/java/com/github/imas/rdflint/validator/impl/DataTypeValidator.java
src/test/java/com/github/imas/rdflint/RdfLintTest.java
src/test/java/com/github/imas/rdflint/utils/StatsTestUtilsTest.java
src/test/resources/testRDFs/datatype_range/datatype_range.rdf

fix #22
implement outlier validation logic by hierarchical clustering.

impl outlier validation

---

README.md
docs/index.md

enrich doc
add articles & case

add articles & case

---

src/main/java/com/github/imas/rdflint/utils/DataTypeUtils.java
src/main/java/com/github/imas/rdflint/validator/impl/DataTypeValidator.java
src/test/java/com/github/imas/rdflint/utils/DataTypeUtilsTest.java

add language type check
implement following checks.
- en: ascii or not
- ja-kana, ja-hira: unicode block

add language type check

---

build.gradle
src/main/java/com/github/imas/rdflint/RdfLint.java
src/main/java/com/github/imas/rdflint/validator/AbstractRdfValidator.java
src/main/java/com/github/imas/rdflint/validator/RdfValidator.java
src/main/java/com/github/imas/rdflint/validator/impl/ShaclValidator.java

add validation function using SHACL
[SHACL (SHape and Constraint Language)](https://www.w3.org/TR/shacl/) is W3C standarded RDF shape and constraint description language.
it can describe data's schema(also called "shape" in RDF) and constraint.
I added [this library](https://github.com/TopQuadrant/shacl) and `ShaclValidator`.

add validation function using SHACL

---

docs/index.md

add PrismDB to case

---

docs/setup.md

Add homebrew install usage to docs.

Add homebrew install usage

---

src/main/java/com/github/imas/rdflint/RdfLint.java

This PR closes #42 .
In the case of a DESCRIBE or CONSTRUCT query, output the result in Turtle format. And a ASK query, output the boolean.

support DESCRIBE/CONSTRUCT/ASK queries

---

README.md
docs/rules.md
docs/setup.md
docs/usage.md
src/main/java/com/github/imas/rdflint/LintProblemFormatter.java
src/main/java/com/github/imas/rdflint/RdfLint.java
src/main/java/com/github/imas/rdflint/ValidationRunner.java
src/main/java/com/github/imas/rdflint/config/RdfLintParameters.java

fix #32 
Implement suppress feature, suppress problem that written in `rdflint-suppress.yml` .

add suppress problems function

---

README.md
docs/setup.md
docs/usage.md

prepare 0.0.9 release
update docs

prepare 0.0.9

---

src/main/java/com/github/imas/rdflint/RdfLint.java
src/main/java/com/github/imas/rdflint/config/RdfLintParameters.java

This PR closes #55 .
To add a command line option of `-outputdir` and a config option of `outputDir`.

add option of outputdir

---

.circleci/config.yml
build.gradle
src/main/java/com/github/imas/rdflint/LintProblem.java
src/main/java/com/github/imas/rdflint/RdfLint.java
src/test/java/com/github/imas/rdflint/LintProblemFormatterTest.java
src/test/java/com/github/imas/rdflint/RdfLintTest.java
src/test/java/com/github/imas/rdflint/validator/impl/ValidatorsTest.java
src/test/resources/testValidatorsImpl/UndefinedSubjectValidator/suppress/rdflint-config.yml
src/test/resources/testValidatorsImpl/UndefinedSubjectValidator/suppress/rdflint-suppress.yml
src/test/resources/testValidatorsImpl/UndefinedSubjectValidator/suppress/undefinedsubject.rdf

for product quality.
- jacoco test coverage rule (80%)
- add followring unit test code
- problem suppress
- problem formatter
- interactive mode

jacoco test coverage rule, and add unit test

---

README.md
docs/setup.md
docs/usage.md
src/main/java/com/github/imas/rdflint/RdfLint.java

prepare 0.0.9 release
update docs

prepare 0.1.0

---

docs/index.md
docs/rules.md

add case.
add pikopikopla.net to case of docs.

add pikopikoplanet to case

---

src/main/java/com/github/imas/rdflint/validator/impl/ShaclValidator.java
src/test/resources/testValidatorsImpl/ShaclValidator/invalidconstraint_global/expected-problems.yml

fix #70   
and SHACL validator message was unkindly
change `ShaclValidator`
fix `ShaclValidator::validateTripleSet` and `ShaclValidator::reportAdditionalProblem`  
and modify `ShaclValidator::buildReportMessage`
**before**
```
WARN  SHACLで定義された制約に違反しています: (https://sparql.crssnky.xyz/imasrdf/RDFs/detail/Shiny_Solisty_Another1 @https://sparql.crssnky.xyz/imasrdf/URIs/imas-schema.ttl#Whose https://sparql.crssnky.xyz/imasrdf/RDFs/detail/Kamiiya_Yukihiro) "Value must be an instance of <https://sparql.crssnky.xyz/imasrdf/URIs/imas-schema.ttl#Idol>" (http://www.w3.org/ns/shacl#ClassConstraintComponent) (triple: https://sparql.crssnky.xyz/imasrdf/RDFs/detail/Shiny_Solisty_Another1 - https://sparql.crssnky.xyz/imasrdf/URIs/imas-schema.ttl#Whose - …
```

change SHACL validator message more kindly

---

README.md
docs/_config.yml
src/main/java/com/github/imas/rdflint/RdfLint.java

prepare 0.1.1 release
updata version on documents

prepare 0.1.1

---

README.md
docs/developer.md
docs/setup.md
docs/usage.md

fix wrong file name in README & docs.
fix document.

fix jarfile name in README & docs

---

src/main/java/com/github/imas/rdflint/validator/impl/UndefinedSubjectValidator.java

fix #82 
remove baseUri null check.

check common schema without baseUri

---

src/main/resources/com/github/imas/rdflint/validator/impl/messages.properties

fix #84 
fix message resource.

fix wrong problem message: remove trailing white space

---

build.gradle
src/main/java/com/github/imas/rdflint/LintProblemLocation.java
src/main/java/com/github/imas/rdflint/RdfLint.java
src/main/java/com/github/imas/rdflint/RdfLintLanguageServer.java
src/test/java/com/github/imas/rdflint/RdfLintLanguageServerTest.java

fix #81
implements language server protocol.

implement language server protocol

---

src/main/java/com/github/imas/rdflint/RdfLintLanguageServer.java

bugfix: windows path problem for language server protocol
change prefix ``file://`` to ``file:///``

bugfix: windows path problem for language server protocol

---

build.gradle
src/main/java/com/github/imas/rdflint/GenerationRunner.java
src/main/java/com/github/imas/rdflint/InteractiveMode.java
src/main/java/com/github/imas/rdflint/LintProblemFormatter.java
src/main/java/com/github/imas/rdflint/RdfLint.java
src/main/java/com/github/imas/rdflint/RdfLintLanguageServer.java
src/main/java/com/github/imas/rdflint/ValidationRunner.java
src/main/java/com/github/imas/rdflint/validator/impl/UndefinedSubjectValidator.java

bugfix: lsp windows problems

---

vscode-rdflint/.gitignore
vscode-rdflint/.vscode/extensions.json
vscode-rdflint/.vscode/launch.json
vscode-rdflint/.vscode/settings.json
vscode-rdflint/.vscode/tasks.json
vscode-rdflint/.vscodeignore
vscode-rdflint/CHANGELOG.md
vscode-rdflint/LICENSE
vscode-rdflint/README.md
vscode-rdflint/package-lock.json
vscode-rdflint/package.json
vscode-rdflint/rdfxml.language-configuration.json
vscode-rdflint/src/extension.ts
vscode-rdflint/src/test/runTest.ts
vscode-rdflint/src/test/suite/extension.test.ts
vscode-rdflint/src/test/suite/index.ts
vscode-rdflint/syntaxes/rdfxml.tmLanguage.json
vscode-rdflint/tsconfig.json
vscode-rdflint/tslint.json

I need to manage rdflint and vscode-rdflint issues in single issue list,
because 2 products are strongly co-operated.
merge repository from vscode-rdflint, and archive vscode-rdflint repository.

merge vscode-rdflint modules

---

.circleci/config.yml
README.md
docs/setup.md
vscode-rdflint/README.md
vscode-rdflint/package.json

guide for vscode users.
add document.

Add vscode rdflint setup docs

---

src/main/java/com/github/imas/rdflint/validator/impl/UndefinedSubjectValidator.java
src/main/resources/rdf/org/w3/shacl.ttl

add subject check under ``http://www.w3.org/ns/shacl#``
add shacl.ttl

add shacl to undefined subject validator

---

README.md

Provide a solution to #53 .
Add a guide to GitHub Actions.

add guide to GitHub Actions

---

build.gradle

fix #103 
upgrade groovy version.

upgrade groovy

---

src/main/java/com/github/imas/rdflint/RdfLint.java
src/main/java/com/github/imas/rdflint/RdfLintLanguageServer.java

add config search path

---

src/main/java/com/github/imas/rdflint/validator/impl/UndefinedSubjectValidator.java
src/test/resources/testValidatorsImpl/UndefinedSubjectValidator/turtle_undefinedsubject_url/expected-problems.yml
src/test/resources/testValidatorsImpl/UndefinedSubjectValidator/turtle_undefinedsubject_url/rdflint-config.yml
src/test/resources/testValidatorsImpl/UndefinedSubjectValidator/turtle_undefinedsubject_url/undefinedsubject_url.ttl

fix #95 
implements load subject check dataset from url.

add undefined subject check from url

---

docs/config.md
docs/rules.md

add dcouments for #95
add documents.

docs: add undefined subject check from url

---

README.md
docs/_config.yml
src/main/java/com/github/imas/rdflint/RdfLint.java
vscode-rdflint/package.json
vscode-rdflint/src/extension.ts

prepare release 0.1.3
update version number.

prepare 0.1.3

---

src/main/java/com/github/imas/rdflint/RdfLint.java
src/main/java/com/github/imas/rdflint/parser/RdflintParserRdfxml.java
src/main/java/com/github/imas/rdflint/parser/RdflintParserTurtle.java
src/main/java/com/github/imas/rdflint/validator/impl/UndefinedSubjectValidator.java
src/test/java/com/github/imas/rdflint/RdfLintTest.java

#112 
- fix load config function's null return.
- add undefined subject validator null check.

fix strange null warnings

---

src/main/java/com/github/imas/rdflint/validator/impl/UndefinedSubjectValidator.java
src/test/resources/testValidatorsImpl/UndefinedSubjectValidator/turtle_undefinedsubject_notfound_url/rdflint-config.yml
src/test/resources/testValidatorsImpl/UndefinedSubjectValidator/turtle_undefinedsubject_notfound_url/undefinedsubject_url.ttl

fix #111 
- fix error handling
- add test code

bugfix: not found url exception in UndefinedSubjectValidator

---

build.gradle
gradle/wrapper/gradle-wrapper.properties
src/main/java/com/github/imas/rdflint/RdfLint.java

support latest spotbugs, gradle, pmd.
upgrade toolversions in build.gradle.

upgrade spotbugs

---

example/dataset/rdflint-config.yml
src/main/java/com/github/imas/rdflint/ConfigurationLoader.java
src/main/java/com/github/imas/rdflint/InteractiveMode.java
src/main/java/com/github/imas/rdflint/RdfLint.java
src/main/java/com/github/imas/rdflint/RdfLintLanguageServer.java
src/main/java/com/github/imas/rdflint/config/RdfLintParameters.java
src/test/java/com/github/imas/rdflint/ConfigurationLoaderTest.java
src/test/java/com/github/imas/rdflint/InteractiveModeTest.java
src/test/java/com/github/imas/rdflint/RdfLintTest.java
src/test/java/com/github/imas/rdflint/validator/impl/ValidatorsTest.java

enable configuration reloading on interactive mode.
implements configuration reloading, when input reload command.

config reloading for interactive mode

---

src/main/java/com/github/imas/rdflint/parser/RdflintParserBuilder.java
src/main/java/com/github/imas/rdflint/parser/RdflintParserErrorHandler.java
src/main/java/com/github/imas/rdflint/parser/RdflintParserRdfxml.java
src/main/java/com/github/imas/rdflint/parser/RdflintParserTurtle.java
src/main/java/com/github/imas/rdflint/validator/impl/RdfSyntaxValidator.java
src/test/resources/testValidatorsImpl/RdfSyntaxValidator/invalidxml/expected-problems.yml
src/test/resources/testValidatorsImpl/RdfSyntaxValidator/turtle_invalid/expected-problems.yml

refactor parser

---

README.md
docs/_config.yml
src/main/java/com/github/imas/rdflint/RdfLint.java
vscode-rdflint/package.json
vscode-rdflint/src/extension.ts

prepare release 0.1.4
change version number.

prepare-0.1.4

---

src/main/java/com/github/imas/rdflint/RdfLintLanguageServer.java
vscode-rdflint/CHANGELOG.md
vscode-rdflint/package-lock.json

bugfix: Windows Language Server path problem
wrong: path separetor & regex is ¥¥¥¥
fix: path separator is ¥, path separator regex is ¥¥¥¥

bugfix: Windows Language Server path problem

---

src/main/java/com/github/imas/rdflint/validator/impl/UndefinedSubjectValidator.java
src/main/resources/rdf/org/schema/11.01/schemaorg-all-http.ttl

catch up latest schema.org
add schme.org 11.0 rdf

upgrade schema.org 11.01

---

README.md
docs/_config.yml
src/main/java/com/github/imas/rdflint/RdfLint.java
vscode-rdflint/package-lock.json
vscode-rdflint/package.json
vscode-rdflint/src/extension.ts

for release
change rdflint version, in documents and properties.

prepare 0.1.5

---

.github/workflows/ci.yaml
.gitignore
README.md
docs/usage.md

add explanation of dotidea branch for IDE settings.
refactor readme

Refactor README - about dotidea branch

---

README.md
docs/_config.yml
docs/config.md
docs/developer.md
docs/index.md
docs/privacy.md
docs/rules.md
docs/setup.md
docs/usage.md

for international user
#134
Make user guide in English, and Japanese user guide will archive.

users guide in English (working)

---

build.gradle

Upgrade jline for #137

---

build.gradle
gradle/wrapper/gradle-wrapper.properties

remove jcenter dependencies, because jcenter was closed.
remove jcenter from build.gradle.

remove jcenter

---

README.md
docs/index.md

update users list - pikopikoplanet is closed.
update docs.

update docs: pikopikoplanet closed

---

README.md
docs/_config.yml
src/main/java/com/github/imas/rdflint/RdfLint.java
vscode-rdflint/package-lock.json
vscode-rdflint/package.json
vscode-rdflint/src/extension.ts

prepare-0.2.0

---

README.md
docs/_config.yml
src/main/java/com/github/imas/rdflint/RdfLint.java
vscode-rdflint/package-lock.json
vscode-rdflint/package.json
vscode-rdflint/src/extension.ts

prepare-0.2.1

---

docs/index.md

add LuciaDB to users information.
_Links to blog posts, patterns, libraries or addons used to solve this problem_

add LuciaDB to docs/users

---

install/install.sh
install/uninstall.sh

homebrew-rdflint alternate solution #151
add install script

feat: add install script
